version: 1
name: production_meeting_slide_prompt
description: "docs/Production_meeting.html を雛形にしたHTMLスライド生成プロンプト"
inputs:
  meeting_title: "<会議タイトル>"
  meeting_subtitle: "<サブタイトル>"
  company_name: "<会社名>"
  date_label: "<YYYY.MM.DD (ddd)>"
  footer_period: "<YYYY年M月度 生産会議>"
  theme:
    primary: "#2563eb"
    secondary: "#10b981"
    accent: "#f59e0b"
    neutral: "#0f172a"
  agenda:
    - "<議題1>"
    - "<議題2>"
    - "<議題3>"
    - "<議題4>"
    - "<議題5>"
  slides:
    orders:
      summary_table:
        - { period: "当月 (確定)", amount_million: 0.0, plan_diff: "+0.0%", mom: "+100%" }
        - { period: "次月 (見込)", amount_million: 0.0, plan_diff: "+0.0%", mom: "+100%" }
      order_trend: ["<12ヶ月の受注推移: 月と値>"]
      load_trend: ["<12ヶ月の負荷推移: 月/スイッチ/コード>"]
      customer_share: ["<顧客別構成: ラベル/比率/色>"]
      change_factors: ["<受注変動要因: 見出し/説明/増減>"]
    production:
      plan_vs_actual: ["<品目/期間/計画/実績/差異/達成率>"]
      delay_reasons: ["<遅延要因: 順位/見出し/説明>"]
    procurement:
      risks: ["<部品/状況/影響/対応>"]
    personnel:
      staffing: ["<工程/負荷/人員/能力/過不足>"]
    supplier:
      suppliers: ["<仕入先名/説明/12ヶ月データ/色>"]
    quality:
      kpis: ["<指標/値/補足>"]
      incidents: ["<発生日/内容/原因/対策/ステータス>"]
    summary:
      evaluation: "<総評テキスト>"
      risks: ["<リスク1>", "<リスク2>"]
      actions: ["<アクション: タイトル/説明>"]
